# Generated by Django 4.0.4 on 2022-05-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnpurchase',
            options={'ordering': ['-time_of_request'], 'verbose_name': 'Возврат покупки', 'verbose_name_plural': 'Возврат покупок'},
        ),
    ]
